#!/usr/bin/env bash
#
# Optional macOS LaunchAgent management for layad.
#
# Nothing here runs automatically: the service is only installed, inspected or
# removed when this script is invoked with the matching command. It never
# touches plists it does not own and never unloads unrelated services.
#
# Usage:
#   scripts/service.sh install     write and load the LaunchAgent
#   scripts/service.sh uninstall   unload and remove our LaunchAgent
#   scripts/service.sh status      show whether it is installed/loaded
#   scripts/service.sh plist       print the plist without writing it
#
# Environment overrides:
#   LAYAD_LABEL   bundle label              (default dev.layad.daemon)
#   LAYAD_BIND    bind address             (default 127.0.0.1:8787)
#   LAYAD_DEVICE  cpu|mps|cuda|auto        (default cpu)
#   LAYAD_CHECKPOINT english|multilingual|typed-decisions (default english;
#                    a non-English checkpoint selects that model subfolder)
#   LAYAD_LOG     tracing filter           (default info)
#   LAYAD_HOME_DIR  runtime home (model/cache/logs); defaults to <repo>/.layad
#   LAYAD_LAUNCHCTL  launchctl binary to use (tests point this at a stub)
#   LAYAD_PLIST_DIR  LaunchAgents directory (tests point this at a temp HOME)
#
# Ownership: a plist is ours only when it carries our generated-file marker
# *and* names this worktree's runtime home. Anything else at the same label is
# left alone, loaded or not.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LABEL="${LAYAD_LABEL:-dev.layad.daemon}"
BIND="${LAYAD_BIND:-127.0.0.1:8787}"
DEVICE="${LAYAD_DEVICE:-cpu}"
CHECKPOINT="${LAYAD_CHECKPOINT:-english}"
LOG_FILTER="${LAYAD_LOG:-info}"
LAYAD_HOME_DIR="${LAYAD_HOME_DIR:-$ROOT/.layad}"
LAUNCHCTL="${LAYAD_LAUNCHCTL:-launchctl}"
PLIST_DIR="${LAYAD_PLIST_DIR:-$HOME/Library/LaunchAgents}"
PLIST="$PLIST_DIR/$LABEL.plist"

# Marker written into plists this script owns, so an unmanaged file at the same
# path is never overwritten or removed.
MARKER="<!-- generated by layad scripts/service.sh -->"
# Second half of the ownership proof: a digest of the exact runtime home this
# worktree uses. A plist generated by a *different* worktree carries the same
# generic marker, so the marker alone must never be enough to claim or delete a
# file. The digest keeps the comment XML-clean for homes containing &, < or >.
HOME_MARKER="<!-- layad-home-digest: "
home_digest="$(printf '%s' "$LAYAD_HOME_DIR" | cksum)"
OWNER_COMMENT="$HOME_MARKER${home_digest%% *} -->"

PYTHON="$ROOT/.venv/bin/python"
WORKER="$ROOT/python/worker.py"
BINARY="$ROOT/target/release/layad"
MODEL_DIR="$LAYAD_HOME_DIR/model"
HF_HOME_DIR="$LAYAD_HOME_DIR/hf"
STDOUT_LOG="$LAYAD_HOME_DIR/layad.log"
STDERR_LOG="$LAYAD_HOME_DIR/layad.err.log"

log() { printf '[service] %s\n' "$*" >&2; }
die() {
  printf '[service] ERROR: %s\n' "$*" >&2
  exit 1
}

# ------------------------------------------------------------ config validation

# A valid launchd label: dot-separated components of [A-Za-z0-9_-], so it can
# never escape the plist directory or smuggle options into launchctl.
case "$LABEL" in
  '' | *[!A-Za-z0-9._-]* | .* | *..* | *.) die "LAYAD_LABEL must be dotted components of letters, digits, '_' and '-' (got '$LABEL')" ;;
esac
case "$DEVICE" in
  cpu | mps | cuda | auto) ;;
  *) die "LAYAD_DEVICE must be cpu, mps, cuda or auto (got '$DEVICE')" ;;
esac
case "$CHECKPOINT" in
  english | multilingual | typed-decisions) ;;
  *) die "LAYAD_CHECKPOINT must be english, multilingual or typed-decisions (got '$CHECKPOINT')" ;;
esac

# --------------------------------------------------------------- plist helpers

# XML-escape one value: &, <, >, quotes and apostrophes are all legal in paths
# and all break XML if passed through.
xml_escape() {
  printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/"/\&quot;/g' -e "s/'/\\&apos;/g"
}

plist_paths() {
  [[ "$PYTHON" == /* ]] || die "python path must be absolute: $PYTHON"
  [[ "$WORKER" == /* ]] || die "worker path must be absolute: $WORKER"
  [[ "$BINARY" == /* ]] || die "binary path must be absolute: $BINARY"
  [[ "$LAYAD_HOME_DIR" == /* ]] || die "runtime home must be absolute: $LAYAD_HOME_DIR"
}

render_plist() {
  plist_paths
  printf '%s\n' '<?xml version="1.0" encoding="UTF-8"?>'
  printf '%s\n' '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
  printf '%s\n' '<plist version="1.0">'
  printf '%s\n' '<dict>'
  printf '  <key>Label</key>\n  <string>%s</string>\n' "$(xml_escape "$LABEL")"
  printf '  %s\n' "$MARKER"
  printf '  %s\n' "$OWNER_COMMENT"
  printf '%s\n' '  <key>ProgramArguments</key>' '  <array>'
  printf '    <string>%s</string>\n' "$(xml_escape "$BINARY")"
  printf '    <string>%s</string>\n' "$(xml_escape "--bind")"
  printf '    <string>%s</string>\n' "$(xml_escape "$BIND")"
  printf '    <string>%s</string>\n' "$(xml_escape "--python")"
  printf '    <string>%s</string>\n' "$(xml_escape "$PYTHON")"
  printf '    <string>%s</string>\n' "$(xml_escape "--worker-script")"
  printf '    <string>%s</string>\n' "$(xml_escape "$WORKER")"
  printf '    <string>%s</string>\n' "$(xml_escape "--model")"
  printf '    <string>%s</string>\n' "$(xml_escape "$MODEL_DIR")"
  printf '    <string>%s</string>\n' "$(xml_escape "--checkpoint")"
  printf '    <string>%s</string>\n' "$(xml_escape "$CHECKPOINT")"
  printf '    <string>%s</string>\n' "$(xml_escape "--device")"
  printf '    <string>%s</string>\n' "$(xml_escape "$DEVICE")"
  printf '    <string>%s</string>\n' "$(xml_escape "--log")"
  printf '    <string>%s</string>\n' "$(xml_escape "$LOG_FILTER")"
  printf '%s\n' '  </array>'
  printf '%s\n' '  <key>EnvironmentVariables</key>' '  <dict>'
  printf '    <key>HF_HOME</key>\n    <string>%s</string>\n' "$(xml_escape "$HF_HOME_DIR")"
  printf '    <key>HF_HUB_OFFLINE</key>\n    <string>1</string>\n'
  printf '    <key>TRANSFORMERS_OFFLINE</key>\n    <string>1</string>\n'
  printf '%s\n' '  </dict>'
  printf '  <key>WorkingDirectory</key>\n  <string>%s</string>\n' "$(xml_escape "$ROOT")"
  printf '  <key>RunAtLoad</key>\n  <true/>\n'
  printf '  <key>StandardOutPath</key>\n  <string>%s</string>\n' "$(xml_escape "$STDOUT_LOG")"
  printf '  <key>StandardErrorPath</key>\n  <string>%s</string>\n' "$(xml_escape "$STDERR_LOG")"
  printf '  <key>KeepAlive</key>\n  <dict>\n    <key>SuccessfulExit</key>\n    <false/>\n  </dict>\n'
  printf '%s\n' '</dict>' '</plist>'
}

require_darwin() {
  [[ "$(uname -s)" == "Darwin" ]] || die "launchd integration is macOS-only; run the daemon in the foreground instead"
}

is_loaded() {
  "$LAUNCHCTL" list "$LABEL" >/dev/null 2>&1
}

# Ours = our marker AND our exact runtime home. A plist written by a sibling
# worktree carries the marker but not this home, so it is never ours.
is_ours() {
  [[ -f "$PLIST" ]] &&
    grep -qF "$MARKER" "$PLIST" &&
    grep -qF "$OWNER_COMMENT" "$PLIST"
}

# Looks generated by this project but names another worktree's runtime home.
is_foreign_plist() {
  [[ -f "$PLIST" ]] && grep -qF "$MARKER" "$PLIST" && ! is_ours
}

# Unload and report honestly: a failed unload is tolerated only when nothing is
# loaded for our label afterwards.
unload_or_fail() {
  local context="$1"
  if ! "$LAUNCHCTL" unload "$PLIST" >/dev/null 2>&1; then
    if is_loaded; then
      die "$context: launchctl unload failed and $LABEL is still loaded"
    fi
    log "$context: launchctl unload reported failure but $LABEL is not loaded; continuing"
  fi
}

cmd_install() {
  require_darwin
  [[ -x "$BINARY" ]] || die "$BINARY is missing; run scripts/setup.sh first"
  [[ -x "$PYTHON" ]] || die "$PYTHON is missing; run scripts/setup.sh first"
  mkdir -p "$PLIST_DIR" "$LAYAD_HOME_DIR"
  if [[ -f "$PLIST" ]] && ! is_ours; then
    if is_foreign_plist; then
      die "$PLIST belongs to another layad worktree (home not '$LAYAD_HOME_DIR'); refusing to touch it"
    fi
    die "$PLIST exists and is not managed by layad; refusing to overwrite it"
  fi
  if [[ ! -f "$PLIST" ]] && is_loaded; then
    die "$LABEL is loaded but $PLIST is not a layad plist; refusing to take over a service we do not own"
  fi
  render_plist >"$PLIST.tmp"
  mv "$PLIST.tmp" "$PLIST"
  log "wrote $PLIST"
  "$LAUNCHCTL" unload "$PLIST" >/dev/null 2>&1 || true
  if "$LAUNCHCTL" load "$PLIST"; then
    log "loaded $LABEL"
  else
    log "could not load $LABEL; inspect with: launchctl load -w '$PLIST'"
    return 1
  fi
}

cmd_uninstall() {
  if [[ ! -f "$PLIST" ]]; then
    log "no plist at $PLIST; nothing to remove"
    return 0
  fi
  if ! is_ours; then
    if is_foreign_plist; then
      die "$PLIST belongs to another layad worktree (home not '$LAYAD_HOME_DIR'); refusing to touch it"
    fi
    die "$PLIST is not managed by layad; refusing to touch it"
  fi
  unload_or_fail "uninstall"
  rm -f "$PLIST"
  log "removed $PLIST"
}

cmd_status() {
  if [[ ! -f "$PLIST" ]]; then
    log "not installed (no $PLIST)"
    return 1
  fi
  if ! is_ours; then
    if is_foreign_plist; then
      die "$PLIST belongs to another layad worktree (home not '$LAYAD_HOME_DIR')"
    fi
    die "$PLIST exists but is not managed by layad"
  fi
  log "installed at $PLIST (checkpoint: $CHECKPOINT, home: $LAYAD_HOME_DIR)"
  if is_loaded; then
    log "loaded"
  else
    log "not loaded"
  fi
}

case "${1:-}" in
  install) cmd_install ;;
  uninstall) cmd_uninstall ;;
  status) cmd_status ;;
  plist) render_plist ;;
  "" | -h | --help)
    sed -n '2,29p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    ;;
  *) die "unknown command '${1}'; expected install, uninstall, status or plist" ;;
esac
